spring.application.name=file-watcher-service
spring.threads.virtual.enabled=true

server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8081/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

file.incoming-path=C:\\Users\\wiratama.paramasatya\\Downloads\\incoming\\

client.excel-generator-base-url=http://excel-generator-service
